1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.  


In [6]:
import numpy as np

# Create a 1D NumPy array with integers from 1 to 20
arr = np.arange(1, 21)

# a. Calculate sum, mean, median, and standard deviation
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_median = np.median(arr)
arr_std = np.std(arr)

# b. Find indices of elements greater than 10
indices = np.where(arr > 10)[0]

# Display results
print("Array:", arr)
print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Median:", arr_median)
print("Standard Deviation:", arr_std)
print("Indices of elements > 10:", indices)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]


2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array. 

In [14]:
# 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.
arr_2d = np.arange(1,17).reshape(4,4)

# a. Print the array.
print("Original 4x4 Array:\n", arr_2d)

# b. Find the transpose of the array. 
transpose = arr_2d.T
print("Transpose of original Array:\n", transpose)

# c. Calculate the row-wise and column-wise sums of the array. 
row_sum = np.sum(arr_2d, axis=1)
col_sum = np.sum(arr_2d, axis=0)
print("Row sum of the original Array:", row_sum)
print("Column sum of the original Array:", col_sum)

Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose of original Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row sum of the original Array: [10 26 42 58]
Column sum of the original Array: [28 32 36 40]


3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.


In [ ]:
np.random.seed(0)

# Create two 3x3 arrays with random integers between 1 and 20
A = np.random.randint(1, 21, size=(3, 3))
B = np.random.randint(1, 21, size=(3, 3))

# a. Element-wise operations
add_result = A + B
sub_result = A - B
mul_result = A * B  

# b. Dot product
dot_product = np.dot(A, B)

# Display results
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nElement-wise Addition:\n", add_result)
print("\nElement-wise Subtraction:\n", sub_result)
print("\nElement-wise Multiplication:\n", mul_result)
print("\nDot Product:\n", dot_product)

Array A:
 [[13 16  1]
 [ 4  4  8]
 [10 20 19]]

Array B:
 [[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]

Element-wise Addition:
 [[18 23 14]
 [ 6 11 16]
 [25 38 25]]

Element-wise Subtraction:
 [[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]

Element-wise Multiplication:
 [[ 65 112  13]
 [  8  28  64]
 [150 360 114]]

Dot Product:
 [[112 221 303]
 [148 200 132]
 [375 552 404]]


4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

In [16]:
# Create a 1D array of size 12
arr_1d = np.arange(1, 13)

# Reshape it into a 3x4 2D array
arr_2d = arr_1d.reshape(3, 4)

# Slice the first two rows and last two columns
sliced = arr_2d[:2, -2:]

# Display results
print("Original 1D Array:", arr_1d)
print("\nReshaped 3x4 Array:\n", arr_2d)
print("\nSliced Array (first 2 rows, last 2 columns):\n", sliced)

Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
